# Generated by Django 3.1.4 on 2020-12-10 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('signature', models.ImageField(upload_to='signatures')),
            ],
        ),
    ]
