# Generated by Django 3.1.4 on 2020-12-13 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('esignature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureString',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('signature', models.CharField(max_length=1023)),
            ],
        ),
        migrations.RenameModel(
            old_name='Signature',
            new_name='SignatureImageUrl',
        ),
    ]
