# Generated by Django 3.1.4 on 2020-12-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esignature', '0002_auto_20201213_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturestring',
            name='signature',
            field=models.CharField(max_length=8191),
        ),
    ]
